name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: daniel-1

    steps:

      - name: List files in the repository
        run: ls -la

      - name: Print working directory
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: adirdevops
          password: Aa12345678

      - name: Build Docker Image
        run: |
          docker build -t adirdevops/webapplication1:latest -f ./Dockerfile .

      - name: Push Docker Image
        run: |
          docker push adirdevops/webapplication1:latest
