name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: daniel-1

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        shell: pwsh

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapplication1:latest -f ./Dockerfile .
        shell: pwsh

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/webapplication1:latest
        shell: pwsh