name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: daniel-1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: adirdevops
        password: Aa12345678

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/webapplication1:latest